"""Stable failure codes and exception class for Phase 4 campaign accounting (#120).

Every failure code is a stable string constant. `CampaignAccountingError` is
raised whenever a ledger, reservation, budget, state transition, or attempt
record violates Phase 4 invariants.
"""

# Cross-document and bundle integrity
CROSS_DOCUMENT_CAMPAIGN_ID_MISMATCH = "CROSS_DOCUMENT_CAMPAIGN_ID_MISMATCH"

# Ledger integrity & fail-closed states
CAMPAIGN_LEDGER_CORRUPT = "CAMPAIGN_LEDGER_CORRUPT"
CAMPAIGN_LEDGER_SEQUENCE_DISCONTINUITY = "CAMPAIGN_LEDGER_SEQUENCE_DISCONTINUITY"
CAMPAIGN_LEDGER_HASH_MISMATCH = "CAMPAIGN_LEDGER_HASH_MISMATCH"
CAMPAIGN_LEDGER_TRUNCATED = "CAMPAIGN_LEDGER_TRUNCATED"

# Reservation & Directory constraints
RESERVATION_EXISTS_FOR_ATTEMPT = "RESERVATION_EXISTS_FOR_ATTEMPT"
ATTEMPT_DIRECTORY_EXISTS = "ATTEMPT_DIRECTORY_EXISTS"
ATTEMPT_NOT_RESERVED = "ATTEMPT_NOT_RESERVED"
RESERVATION_REQUIRED_BEFORE_INVOCATION = "RESERVATION_REQUIRED_BEFORE_INVOCATION"
RESERVATION_NOT_GENUINE = "RESERVATION_NOT_GENUINE"
RESERVATION_NOT_LIVE = "RESERVATION_NOT_LIVE"
RESERVATION_EXPIRED = "RESERVATION_EXPIRED"
RESERVATION_CAMPAIGN_MISMATCH = "RESERVATION_CAMPAIGN_MISMATCH"
RESERVATION_CONFIGURATION_MISMATCH = "RESERVATION_CONFIGURATION_MISMATCH"
RESERVATION_ATTEMPT_MISMATCH = "RESERVATION_ATTEMPT_MISMATCH"
CONFIGURATION_ID_MISMATCH = "CONFIGURATION_ID_MISMATCH"
ATTEMPT_ID_NOT_UUID = "ATTEMPT_ID_NOT_UUID"

# Budget and Policy Ceilings
BUDGET_EXCEEDED_ATTEMPT_SLOTS = "BUDGET_EXCEEDED_ATTEMPT_SLOTS"
BUDGET_EXCEEDED_PROVIDER_INVOCATIONS = "BUDGET_EXCEEDED_PROVIDER_INVOCATIONS"
BUDGET_EXCEEDED_CONFIGURATION_SLOTS = "BUDGET_EXCEEDED_CONFIGURATION_SLOTS"
CAMPAIGN_EXPIRED = "CAMPAIGN_EXPIRED"
CAMPAIGN_NOT_ACTIVE = "CAMPAIGN_NOT_ACTIVE"

# Attempt Lifecycle & State Transitions
ATTEMPT_ALREADY_TERMINAL = "ATTEMPT_ALREADY_TERMINAL"
ATTEMPT_STATE_INVALID_TRANSITION = "ATTEMPT_STATE_INVALID_TRANSITION"
RAW_OUTPUT_MISSING_FOR_CAPTURED_STATE = "RAW_OUTPUT_MISSING_FOR_CAPTURED_STATE"

# Summary projection integrity
CAMPAIGN_SUMMARY_ORPHAN_RESULT = "CAMPAIGN_SUMMARY_ORPHAN_RESULT"
CAMPAIGN_SUMMARY_MISSING_ATTEMPT_DIR = "CAMPAIGN_SUMMARY_MISSING_ATTEMPT_DIR"

# Immutable artifact path confinement
ARTIFACT_FILENAME_INVALID = "ARTIFACT_FILENAME_INVALID"
RAW_OUTPUT_EXTENSION_INVALID = "RAW_OUTPUT_EXTENSION_INVALID"
ARTIFACT_ALREADY_EXISTS = "ARTIFACT_ALREADY_EXISTS"


class CampaignAccountingError(Exception):
    """Raised when a campaign accounting invariant is violated."""

    def __init__(self, failure_code: str, details: str) -> None:
        super().__init__(f"[{failure_code}] {details}")
        self.failure_code = failure_code
        self.details = details
