"""Freeze the stable failure-code set (ADR 0023 / Issue #118 requirement)."""

from __future__ import annotations

from sensemaking_skills.campaign_validation import CAMPAIGN_FAILURE_CODES

FROZEN_CODES = frozenset({
    "CAMPAIGN_PATH_ESCAPE",
    "CAMPAIGN_SYMLINK_CONTAINMENT_VIOLATION",
    "CAMPAIGN_FILESYSTEM_ERROR",
    "CAMPAIGN_POLICY_MISSING",
    "CAMPAIGN_POLICY_SOURCE_PROFILE_INVALID",
    "CAMPAIGN_POLICY_SCHEMA_UNSUPPORTED",
    "CAMPAIGN_POLICY_SCHEMA_INVALID",
    "CAMPAIGN_POLICY_IDENTITY_AMBIGUOUS",
    "CAMPAIGN_POLICY_DIGEST_MALFORMED",
    "CAMPAIGN_POLICY_DIGEST_MISMATCH",
    "CAMPAIGN_APPROVAL_MISSING",
    "CAMPAIGN_APPROVAL_SOURCE_PROFILE_INVALID",
    "CAMPAIGN_APPROVAL_SCHEMA_UNSUPPORTED",
    "CAMPAIGN_APPROVAL_SCHEMA_INVALID",
    "CAMPAIGN_APPROVAL_EXAMPLE_TEMPLATE_NON_OPERATIVE",
    "CAMPAIGN_APPROVAL_PLACEHOLDER_PRESENT",
    "CAMPAIGN_APPROVAL_POLICY_MISMATCH",
    "CAMPAIGN_APPROVER_UNAUTHORIZED",
    "CAMPAIGN_APPROVAL_PROVENANCE_INVALID",
    "CAMPAIGN_APPROVAL_AMBIGUOUS",
    "CAMPAIGN_POLICY_NOT_YET_VALID",
    "CAMPAIGN_POLICY_EXPIRED",
    "CAMPAIGN_POLICY_VALIDITY_WINDOW_INVALID",
    "CAMPAIGN_POLICY_LIMITS_INVALID",
    "CAMPAIGN_CONFIGURATION_MISSING",
    "CAMPAIGN_CONFIGURATION_SOURCE_PROFILE_INVALID",
    "CAMPAIGN_CONFIGURATION_SCHEMA_INVALID",
    "CAMPAIGN_CONFIGURATION_IDENTITY_AMBIGUOUS",
    "CAMPAIGN_CONFIGURATION_ID_MALFORMED",
    "CAMPAIGN_CONFIGURATION_ID_MISMATCH",
    "CAMPAIGN_CONFIGURATION_CAMPAIGN_MISMATCH",
    "CAMPAIGN_CONFIGURATION_ID_NOT_ALLOWED",
    "CAMPAIGN_CONFIGURATION_FRAMEWORK_NOT_ALLOWED",
    "CAMPAIGN_CONFIGURATION_TARGET_NOT_ALLOWED",
    "CAMPAIGN_CONFIGURATION_MODEL_NOT_ALLOWED",
    "CAMPAIGN_CONFIGURATION_ARTIFACT_TYPE_NOT_ALLOWED",
    "CAMPAIGN_INTERNAL_VALIDATION_ERROR",
})


def test_failure_code_set_is_frozen_and_exact():
    assert set(CAMPAIGN_FAILURE_CODES.keys()) == FROZEN_CODES


def test_every_code_carries_campaign_prefix():
    assert all(code.startswith("CAMPAIGN_") for code in CAMPAIGN_FAILURE_CODES)


def test_no_generic_invalid_or_unauthorized_code():
    assert "CAMPAIGN_INVALID" not in CAMPAIGN_FAILURE_CODES
    assert "CAMPAIGN_UNAUTHORIZED" not in CAMPAIGN_FAILURE_CODES


def test_every_code_has_a_non_empty_description():
    assert all(isinstance(v, str) and v.strip() for v in CAMPAIGN_FAILURE_CODES.values())
